### ISSUE TITLE
Benchmark against zstd

### ISSUE THREAD

**Issue by corneliusroemer** [Senikm/terse#1]
Just saw your talk at the symposium. Neat program and ideas and the benchmarks look really great.

There's one general purpose compression algorithm I'd additionally like to see in the benchmark however: Zstd is a relatively novel compression program that has very good properties on the ratio/bandwidth frontier. Much much better than gz up.

It'd be cool if you could benchmark terse also against that method.

Also, I think it'd be best to express compression and decompression speeds in bandwidth of bits per second (uncompressed data) instead of runtime on a particular file.

Bandwidth is easier to compare than runtime.

**Comment by senikm** [comment]
@corneliusroemer Thank you for the suggestions. We plan to incorporate comparisons with zstd in the upcoming version of our preprint. While zstd demonstrates superiority over gzip, TERSE surpasses all of them when compressing diffraction data, owing to its specific tailoring to handle such data.

**Comment by senikm** [comment]
@corneliusroemer Here is the paper with zstd comparison included: https://onlinelibrary.wiley.com/iucr/doi/10.1107/S205327332300760X
